name: Crear y subir imagen docker
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4

      - name: Iniciar sesion en docker
        run: echo "${{ secrets.DOCKER_HUB_TOKEN}}" | docker login -u "kelgaris" --password-stdin

      - name: construir imagen
        run: docker build . -t kelgaris/ejemplo-automatico:latest

      - name: subir imagen
        run: docker push kelgaris/ejemplo-automatico:latest